PR exercício dict
toshikurauchi/processo-seletivo-bolsas-2021 pull request #3
Opened 2021-09-09 21:49 UTC by rafaelcl292

Teste do exercício de dicionário.

2021-09-09 21:56 UTC, rafaelcl292 commented
O teste inclui:
- teste para uma string vazia
- teste para uma palavra sem repetições de caracteres ('zebra')
- teste de duas palavras com caracteres repetidos

2021-09-10 14:08 UTC, toshikurauchi requested changes
Você poderia incluir um teste com caracteres especiais, por favor?

2021-09-10 14:17 UTC, rafaelcl292 commented
Teste com caracteres especiais adicionado.

2021-09-10 14:40 UTC, toshikurauchi commented
Beleza! Só aguardar agora, obrigado!

2021-09-10 14:40 UTC, closed without merging