PR Diego S.
toshikurauchi/processo-seletivo-bolsas-2021 pull request #4
Opened 2021-09-09 21:53 UTC by DiegoSaragozaSilva

2021-09-09 22:52 UTC, DiegoSaragozaSilva commented
Atualização feita antes do review (Não deletei meu código antigo, ele ainda funciona e está lá para ser julgado também)

2021-09-10 13:50 UTC, toshikurauchi commented on exercicio_dicionario/test_solution.py
> +def teste_ocorrencias():
Legal Diego! Nesses casos é interessante utilizar o https://docs.pytest.org/en/6.2.x/parametrize.html porque aí o pytest registra cada um desses casos como um teste diferente. Não precisa implementar para agora, mas vale a pena dar uma olhada.

2021-09-10 14:10 UTC, toshikurauchi requested changes
Você poderia fazer a alteração do `@pytest.mark.parametrize`, por favor?

2021-09-10 14:37 UTC, DiegoSaragozaSilva commented on exercicio_dicionario/test_solution.py
> +def teste_ocorrencias():
Posso sim Toshi!

2021-09-10 15:00 UTC, toshikurauchi commented
Beleza! Agora só aguardar. Obrigado!

2021-09-10 15:00 UTC, closed without merging