Exercício Dicionário - Pytest
toshikurauchi/processo-seletivo-bolsas-2021 pull request #6
Opened 2021-09-09 22:56 UTC by camilamagni

Utilizando o Pytest, foram feitos testes para:

- o exemplo dado no enunciado
- uma string com um único caractere
- uma string vazia
- uma string com caracteres especiais
- uma string com várias repetições de caracteres

2021-09-09 22:58 UTC, camilamagni commented
Utilizando o Pytest, foram feitos testes para:

- o exemplo dado no enunciado
- uma string com um único caractere
- uma string vazia
- uma string com caracteres especiais
- uma string com várias repetições de caracteres

2021-09-10 14:14 UTC, toshikurauchi requested changes

2021-09-10 14:14 UTC, toshikurauchi commented on exercicio_dicionario/solution.py
> +print(primeiras_ocorrencias('abracadabra'))
É realmente uma boa fazer alguns testes da solução, mas isso pode acabar influenciando os testes depois. Antes de enviar o código é sempre uma boa fazer uma limpeza. Você poderia fazer um novo commit apagando o comentário e os prints deste arquivo, por favor?

2021-09-10 14:55 UTC, toshikurauchi commented
Beleza, está ótimo! Agora só aguardar. Obrigado!

2021-09-10 14:55 UTC, closed without merging

2021-09-10 14:56 UTC, camilamagni commented on exercicio_dicionario/solution.py
> +print(primeiras_ocorrencias('abracadabra'))
Posso sim toshi, acabei de dar o novo commit.